### ISSUE TITLE
UCW lacks dependency on Chisel

### ISSUE THREAD

**Issue by rallias** [asiekierka/UnlimitedChiselWorks#60]
UCW has a code dependency on Chisel. However, this is not enforced by a dependency on Chisel, resulting in the following error:

```
java.lang.NoClassDefFoundError: team/chisel/api/IChiselItem
	at pl.asie.ucw.UnlimitedChiselWorksBotany.onPlayerInteract(UnlimitedChiselWorksBotany.java:168)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_543_UnlimitedChiselWorksBotany_onPlayerInteract_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:232)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: team.chisel.api.IChiselItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 27 more
Caused by: java.lang.NullPointerException
```

(and yes, I'm an idiot for forgetting Chisel)

**Comment by asiekierka** [comment]
That is deliberate. You could technically use UCW without Chisel (by writing your own *ucwdefs*), albeit this has not been tested well; this is a bug with the addon, which does not appropriately handle the lack of Chisel's presence.
